site_name: Loom

plugins:
  - entangled

markdown_extensions:
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

theme:
  name: material
  features:
    - content.code.annotate
  palette:
      # Palette toggle for light mode
      - scheme: default
        primary: pink 
        toggle:
          icon: material/brightness-7 
          name: Switch to dark mode
  
      # Palette toggle for dark mode
      - scheme: slate
        primary: pink  
        toggle:
          icon: material/brightness-4
          name: Switch to light mode

extra_javascript:
    - js/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML

