# ~/~ begin <<docs/index.md#examples/rot13.toml>>[init]
[template.echo]
stdout = "${stdout}"
runner = "Bash"
script = "echo ${text}"

[pattern.rot13]
stdout = "${stdout}"
stdin = "${stdin}"
runner = "Bash"
script = "tr a-zA-Z n-za-mN-ZA-M"

[[call]]
template = "echo"
  [call.args]
  stdout = "secret1.txt"
  text = "Uryyb, Jbeyq!"

[[call]]
template = "rot13"
  [call.args]
  stdin = "secret.txt"
  stdout = "msg.txt"

[[task]]
name = "all"
requires = ["msg.txt"]
# ~/~ end
