# ~/~ begin <<docs/index.md#examples/rot13.toml>>[init]
[pattern.echo]
stdout = "${stdout}"
language = "Bash"
script = "echo ${text}"

[pattern.rot13]
stdout = "${stdout}"
stdin = "${stdin}"
language = "Bash"
script = "tr a-zA-Z n-za-mN-ZA-M"

[[call]]
pattern = "echo"
  [call.args]
  stdout = "secret1.txt"
  text = "Uryyb, Jbeyq!"

[[call]]
pattern = "rot13"
  [call.args]
  stdin = "secret.txt"
  stdout = "msg.txt"

[[task]]
name = "all"
dependencies = ["msg.txt"]
# ~/~ end