# ~/~ begin <<docs/index.md#examples/tasks.toml>>[init]
[[task]]
creates = ["hello.txt"]
runner = "Bash"
script = "echo 'Hello, World!' > hello.txt"

[[task]]
name = "all"
requires = ["hello.txt"]

[[task]]
name = "clean"
script = "rm hello.txt"
# ~/~ end
