[environment]
title = "Brei"
subtitle = "a minimal workflow system"

pandoc_args = """
${pandoc_format} ${pandoc_style} ${pandoc_template} ${pandoc_filters} \
-M title='${title}' -M subtitle='${subtitle}' \
-M contents_file='docs/contents.md'"""

pandoc_format = "-s -t html5 --section-divs --toc --toc-depth 2"
pandoc_template = "--template docs/template/template.html"
pandoc_style = "--css dark.css --highlight-style zenburn"
pandoc_filters = """
--lua-filter ${filter_dir}/include-contents.lua \
--lua-filter ${filter_dir}/include.lua \
--lua-filter ${filter_dir}/annotate.lua \
--lua-filter ${filter_dir}/details.lua \
--lua-filter ${filter_dir}/eqnos.lua \
--lua-filter ${filter_dir}/eval.lua \
--lua-filter ${filter_dir}/links.lua"""

filter_dir = "docs/filters"

[[call]]
template = "copy"
collect = "static"
  [call.args]
  srcdir = "docs/template"
  tgtdir = "docs/site"
  basename = ["dark.css", "light.css", "github-mark.svg", "nlesc.svg"]

[template.pandoc]
description = "pandoc `${basename}`"
requires = ["docs/${basename}.md", "docs/template/template.html", "docs/contents.md", "docs/test_coverage.md"]
creates = ["docs/site/${basename}.html"]
script = "pandoc ${pandoc_args} -o 'docs/site/${basename}.html' 'docs/${basename}.md'"

[template.copy]
description = "copy `${basename}`"
requires = ["${srcdir}/${basename}"]
creates = ["${tgtdir}/${basename}"]
script = "cp '${srcdir}/${basename}' '${tgtdir}'"

